---
- name: download libsodium
  unarchive:
    src: https://download.libsodium.org/libsodium/releases/libsodium-{{ libsodium_ver }}.tar.gz
    dest: "{{ workspace }}"
    remote_src: yes
  register: libsodium_dir

- name: install libsodium
  block:
    - name: configure libsodium
      command: ./configure --prefix=/usr
      args:
        chdir: "{{ workspace }}/libsodium-{{ libsodium_ver }}"
      register: libsoconfig
    - name: make libsodium
      command: make
      args:
        chdir: "{{ workspace }}/libsodium-{{ libsodium_ver }}"
    - name: make install
      command: make install
      args:
        chdir: "{{ workspace }}/libsodium-{{ libsodium_ver }}"
    - name: ldconfig
      command: ldconfig
