---
- include: tasks/apt.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 16
- include: tasks/libsodium.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 16
- include: tasks/mbedtls.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 16
- include: tasks/shadowsocks-libev.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 16
