---
- name: Check if mbedtls path exists
  stat: path={{ workspace }}/mbedtls-{{ mbedtls_ver }}
  register: check_mbedtls_path

- name: Download mbedtls
  unarchive:
    src: https://tls.mbed.org/download/mbedtls-{{ mbedtls_ver }}-gpl.tgz
    dest: "{{ workspace }}"
    remote_src: yes
  register: mbedtls_dir
  when: check_mbedtls_path.stat.exists == false

- name: Check if mbedtls installed
  stat: path={{ workspace }}/mbedtls-{{ mbedtls_ver }}/installed
  register: check_mbedtls_path

- name: Install mbedtls
  block:
    - name: Make mbedtls
      command: make SHARED=1 CFLAHS=-fPIC
      args:
        chdir: "{{ workspace }}/mbedtls-{{ mbedtls_ver }}"
    - name: Make install
      command: make DESTDIR=/usr install
      args:
        chdir: "{{ workspace }}/mbedtls-{{ mbedtls_ver }}"
    - name: Ldconfig
      command: ldconfig
    - name: Touch
      command: touch installed
      args:
        chdir: "{{ workspace }}/mbedtls-{{ mbedtls_ver }}"
  when: check_mbedtls_path.stat.exists == false

