---
- name: get installed ss version
  shell: "which ss-server >/dev/null 2>&1 && (ss-server --help | grep '^shadowsocks-libev' | sed -e 's!^shadowsocks-libev \\([0-9\\.]*\\).*!\\1!')"
  changed_when: false
  failed_when: false
  register: ss_libev_installed_ver

- name: Reinstall if need
  set_fact:
    reinstall_ss: true
  when: 'ss_libev_installed_ver.stdout | regex_replace("^.*?([0-9\.]+)$", "\\1") | version_compare(shadowsocks_libev_version, operator="!=")'

- name: git clone shadowsoks-libev
  git:
    repo: 'https://github.com/shadowsocks/shadowsocks-libev'
    dest: "{{  workspace }}/shadowsocks-libev-{{ ss_libev_ver }}"
    version: v{{ ss_libev_ver }}
    recursive: yes
    update: yes
    when: ss_libev_installed_ver|failed or reinstall_ss

- name: build shadowsocks-libev
  block:
    - command: ./autogen.sh
      args:
        chdir: "{{  workspace }}/shadowsocks-libev-{{ ss_libev_ver }}"
    - command: ./configure
      args:
        chdir: "{{  workspace }}/shadowsocks-libev-{{ ss_libev_ver }}"
    - command: make
      args:
        chdir: "{{  workspace }}/shadowsocks-libev-{{ ss_libev_ver }}"
    - command: make install
      args:
        chdir: /root/repo_ss
  when: ss_libev_installed_ver|failed or reinstall_ss

- name: start ss-server
  block:
    - template:
        src: shadowsocks-libev.service
        dest: /usr/lib/systemd/system/
        mode: 755

    - name: ensures shadowsocks-libev dir exists
      file: path=/etc/shadowsocks-libev state=directory

    - template:
        src: shadowsocks.json
        dest: /etc/shadowsocks-libev/config.json

    - name: Start shadowsocks-libev
      systemd:
        name: shadowsocks-libev
        state: started
        enabled: yes
        daemon_reload: yes
